### ISSUE TITLE
Installing SqlTools fails

### ISSUE THREAD

**Issue by domshifter** [SharpeRAD/Cake.SqlTools#11]
Since the 0.1.0 update, installation via the cake addin directive (`#addin "Cake.SqlTools"`) fails:

![build](https://user-images.githubusercontent.com/16257869/31123784-aaf75cc4-a841-11e7-9563-77e8502108a7.png)

It looks like it is caused by the MySql Connector, someone already opened a topic on their [forum](https://forums.mysql.com/read.php?38,659964,659964).

**Comment by andreabalducci** [comment]
Same here. Working on my win10 x64 box and macOS but fails on AppVeyor.

**Comment by andreabalducci** [comment]
note: MySql driver is licensed under GPL while your addin is MIT. Should be loaded dynamically "on demand" not statically linked.

**Comment by jnm2** [comment]
Static linking = ILMerging into a single DLL. Dynamic linking on demand = assembly reference to a separate DLL.

**Comment by jnm2** [comment]
And anyway what you're seeing in this case is Cake eagerly (and dynamically) loading up every DLL it finds in the nupkg, whether the addin references it or not.

**Comment by SharpeRAD** [comment]
I've go back down to 6.9.9 and highlight the different licenses in the ReadMe.

**Comment by SharpeRAD** [comment]
Try v0.1.1

**Comment by domshifter** [comment]
Installation works now, thank you!
