### ISSUE TITLE
Target netstandard2.0 to run with Cake.CoreCLR

### ISSUE THREAD

**Issue by git-man** [SharpeRAD/Cake.SqlTools#12]
It would be cool, if the Cake.CoreCLR compatibility could be added, as stated here:
https://cakebuild.net/blog/2018/02/cake-v0.26.0-released
Due to this only "netstandard2.0" needs to be targeted by the addin.

The misleading error, which appeared to me relating to this issue was: "Error: Failed to install addin 'Cake.SqlTools'."
This misleading message lead me to: https://github.com/cake-build/cake/issues/2011 ... but that's another thing...

Thanks for your support and your great work!

**Comment by SharpeRAD** [comment]
Resolved in v0.2.0
