### ISSUE TITLE
.NetCore Project - Could not load: Cake.SqlTools.0.2.0\lib\net46\MySql.Data.dll 

### ISSUE THREAD

**Issue by thiagoholder** [SharpeRAD/Cake.SqlTools#13]
In a .NetCore project to reference SQL.Tools, an alert occurs: Cake.SqlTools.0.2.0 \ lib \ net46 \ MySql.Data.dll (missing Google.Protobuf, Version = 3.3.0.0, Culture = neutral, PublicKeyToken = a7d26565bac4d604)

**Comment by SharpeRAD** [comment]
Try again with v0.2.1
