### ISSUE TITLE
Does not work with .net core on linux

### ISSUE THREAD

**Issue by frosch95** [SharpeRAD/Cake.SqlTools#18]
This Addin does not work with .net core on linux as the dependencies like Mysql.Data only is packaged for net46.

This results in the following error:
Could not load file or assembly 'MySql.Data, Version=8.0.12.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'. The system cannot find the file specified.

As we use Linux machines for our CI/CD process, support for .net core is very important to us. And we would like to use your addin for mysql queries in this process.

Thanks,
Andi

**Comment by SharpeRAD** [comment]
Try `#addin nuget:?package=Cake.SqlTools&loaddependencies=true`

**Comment by SharpeRAD** [comment]
Better late than never I guess but this is now supported in `v1.0.0+`
