### ISSUE TITLE
NuGet package 0.0.4 can not be installed in build file

### ISSUE THREAD

**Issue by papauorg** [SharpeRAD/Cake.SqlTools#6]
Hi,

I can't install the newly published addin 0.0.4 in my build script. If I integrate it via:
`#addin "Cake.SqlTools"`
I get an error when running the script:

> Installing addins...
> Unable to resolve dependency 'Npgsql.dll'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.
> NuGet exited with 1
> Could not find any assemblies compatible with .NETFramework,Version=v4.5.
> Error: Failed to install addin 'Cake.SqlTools'.

If I specify the version 0.0.3 explicitly it works fine.
`#addin "nuget:?package=Cake.SqlTools&version=0.0.3"`

Best regards

**Comment by SharpeRAD** [comment]
Sorry was in a rush yesterday and accepted a bad PR #5 I shouldn't have. It won't find that reference as nuget package names don't end in .dll 😞 

I'll revert it tonight.

**Comment by papauorg** [comment]
Ok, thanks! I'll stick with the explicit version till then. 😄

**Comment by N41m0r** [comment]
Sorry it's my fault, i pushed too fast yesterday
